server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hadesfranklyn/config-server-spring-cloud
          #username: username (if it was private repository)
          #password: password (if it was private repository)
          default-label: main
          search-paths:
          - 'greeting-service'